import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "antd/dist/reset.css";
import Header from "@/component/Header";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import AppProvider from "@/context/app.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AppProvider>
      <html lang="en">
        <body className={inter.className}>
          <ConfigProvider
            theme={{
              token: {
                // Seed Token
                colorPrimary: "#2196F3",
              },
            }}
          >
            <Header />
            <div className="">
              <AntdRegistry>{children}</AntdRegistry>
            </div>
          </ConfigProvider>
        </body>
      </html>
    </AppProvider>
  );
}
