import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "antd/dist/reset.css";
import Header from "@/component/Header";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import AppProvider from "@/context/app.context";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS project",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <AppProvider>
      <html lang="en">
        <body className={inter.className}>
          <ConfigProvider
            theme={{
              token: {
                // Seed Token
                colorPrimary: "#2196F3",
              },
            }}
          >
            <NextIntlClientProvider messages={messages}>
              <Header />
              <div className="">
                <AntdRegistry>{children}</AntdRegistry>
              </div>
            </NextIntlClientProvider>
          </ConfigProvider>
        </body>
      </html>
    </AppProvider>
  );
}
